### ISSUE TITLE
Обновление конкретных контрактов

### ISSUE THREAD

**Issue by bastshoes** [alryaz/hass-mosoblgaz#1]
При указании контрактов в файле конфигурации возникает ошибка

```
mosoblgaz:
  ...
  contracts:
    # Обновлять всё связанное с контрактом (счётчики, квитанции, и т.д.)
    135112512: true
    
    # Отключить добавление контракта
    5612341421: false
```
```
2020-06-24 19:05:43 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mosoblgaz platform for sensor

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mosoblgaz/sensor.py", line 188, in async_setup_entry
    result = await update_call()
  File "/config/custom_components/mosoblgaz/sensor.py", line 99, in _entity_updater
    if not use_filter or user_cfg[CONF_CONTRACTS][contract_id].get(CONF_METERS, True):
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by alryaz** [comment]
Немного поменялась конфигурация (см. README.md), но в целом ошибка исправлена.
Каких-то жёстких несовместимостей нет (поскольку, оказывается, фильтрация с использованием исключительно значений типа _истина_ и _ложь_ не работала вовсе).
