### ISSUE TITLE
C выходом новых версий НА увеличивается количество ошибок

### ISSUE THREAD

**Issue by conrad66** [alryaz/hass-mosoblgaz#4]
Traceback (most recent call last):
  File "/opt/homeassistant/config/custom_components/mosoblgaz/sensor.py", line 151, in _entity_updater
    meter_entity.async_schedule_update_ha_state(force_refresh=True)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 438, in async_schedule_update_ha_state
    assert self.hass is not None
AssertionError
p.s.
также перестал работать invoice, пришлось отключить
p.s.s.
Жаль что автор "забил" на отличный компонет :(

**Comment by alryaz** [comment]
Здравствуйте, @conrad666! Напишите в Telegram (@alryaz), попробуем решить проблему.
У меня нет аккаунта Мособлгаза, чтобы производить тестирование.

**Comment by alryaz** [comment]
Исправлено в v0.1.0b2
